name: Release Dev Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true


jobs:
  setup:
    runs-on: ubuntu-24.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Install Podman
        run: sudo apt update && sudo apt install -y podman
  release:
    runs-on: ubuntu-24.04
    needs: setup
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Release
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          echo "Start dev build"
          docker run --privileged --rm tonistiigi/binfmt --install all
          podman manifest create build
          podman build --format docker --build-arg BUILD_VERSION_ARG=${VERSION} --manifest localhost/build --platform linux/amd64,linux/arm64,linux/arm/v7 .
          podman manifest push localhost/build docker://docker.io/bbernhard/signal-cli-rest-api:${VERSION}-dev
          podman manifest push localhost/build docker://docker.io/bbernhard/signal-cli-rest-api:latest-dev
